git:
  commit_prefix:
    - ["comment", "Documentations", ":bulb:"]  # 💡
    - ["typos", "Documentations", ":pencil2:"]  # ✏️
  commit_prefix_group:
    - ["Features", ":tada:"]  # 🎉
    - ["Documentations", ":book:"]  # 📖
  commit_prefix_force_fix: true
