git:
  commit_prefix:
    - ["comment", "Documents", ":bulb:"]  # 💡
    - ["typos", "Documents", ":pencil2:"]  # ✏️
  commit_prefix_group:
    - ["Features", ":tada:"]  # 🎉
    - ["Documents", ":book:"]  # 📖
  commit_prefix_force_fix: true
version:
  commit_msg_format: "- {subject}"
