-   id: shelf-commit-msg
    name: shelf prepare commit message
    description: Automatically prepare commit message with emoji prefix.
    entry: shelf git cm
    args: ["--edit", "-output-file"]
    language: python
    always_run: true
    minimum_pre_commit_version: 2.9.2
    stages: [commit-msg]
