-   id: clishelf
    name: clishelf
    description: Automatically prepare commit message with emoji prefix.
    entry: shelf git cm -e -l -o
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 2.9.2
