name: pre-commit

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: Ref of the pre-commit
        required: false
        default: 'main'
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - '*.md'
      - '.pre-commit-config.yaml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  tests-install-hook:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Python Dependencies without Cache
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          pip install -U pip
          pip install -U pre-commit
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

      - name: Set Rev name
        run: |
          if [[ "${{ github.event.inputs.ref_name }}" == 'default' || "${{ github.event.inputs.ref_name }}" == "" ]]; then
            REF_NAME=${{ github.ref_name }}
          else
            REF_NAME=${{ github.event.inputs.ref_name }}
          fi
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV

      - name: Create Pre-commit config file
        run: |
          cat <<EOF > .pre-commit-config.yaml
          default_install_hook_types: [commit-msg]
          repos:
            - repo: https://github.com/korawica/clishelf
              rev: ${{ env.REF_NAME }}
              hooks:
                - id: shelf-commit-msg
                  stages: [commit-msg]
          EOF

      - name: Debug pre-commit file & List all files
        run: |
          echo "cat .pre-commit-config.yaml"
          cat .pre-commit-config.yaml
          ls -lA

      - name: Start testing Pre-commit hook
        run: |
          git config --global user.email "korawica@github.actions"
          git config --global user.name "Testing Git on Pre-commit CI"
          pre-commit install
          git add .
          git commit -am "test: test pre-commit hook able to run"
